kind: pipeline
name: react-reference-app

steps:

  - name: publish-docker
    image: plugins/gcr
    settings:
      repo: bip-nullfem/react-reference-app
      registry: eu.gcr.io
      tags: "${DRONE_BRANCH}-latest"
      json_key:
        from_secret: gcr_credentials
    when:
      branch:
      - drone-setup

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
#      channel: bip-ci-test -- Choosing channel is not enabled yet
    when:
      status: [ success, failure ]

---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url